// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.songs.add
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Serialize, Deserialize};
use crate::pet_nkp::radio::RadioSnapshot;
use crate::pet_nkp::radio::Song;
use crate::pet_nkp::radio::SongUrlSource;

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Add<'a> {
    ///Remote audio sources to import in order.
    #[serde(borrow)]
    pub sources: Vec<SongUrlSource<'a>>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct AddOutput<'a> {
    ///Number of sources accepted and queued for asynchronous download. Imports complete later and surface via the radio websocket / queue.list rather than in this response.
    pub accepted: i64,
    #[serde(borrow)]
    pub snapshot: RadioSnapshot<'a>,
    ///Imported or deduplicated songs. Empty when imports are still in progress.
    #[serde(borrow)]
    pub songs: Vec<Song<'a>>,
}


#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic
)]

#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum AddError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "AdminRequired")]
    AdminRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
    #[serde(rename = "InvalidUrl")]
    InvalidUrl(Option<CowStr<'a>>),
    #[serde(rename = "DownloadFailed")]
    DownloadFailed(Option<CowStr<'a>>),
    #[serde(rename = "UnsupportedAudio")]
    UnsupportedAudio(Option<CowStr<'a>>),
}

impl core::fmt::Display for AddError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AdminRequired(msg) => {
                write!(f, "AdminRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidUrl(msg) => {
                write!(f, "InvalidUrl")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::DownloadFailed(msg) => {
                write!(f, "DownloadFailed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::UnsupportedAudio(msg) => {
                write!(f, "UnsupportedAudio")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for pet.nkp.radio.songs.add
pub struct AddResponse;
impl jacquard_common::xrpc::XrpcResp for AddResponse {
    const NSID: &'static str = "pet.nkp.radio.songs.add";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = AddOutput<'de>;
    type Err<'de> = AddError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for Add<'a> {
    const NSID: &'static str = "pet.nkp.radio.songs.add";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = AddResponse;
}

/// Endpoint type for pet.nkp.radio.songs.add
pub struct AddRequest;
impl jacquard_common::xrpc::XrpcEndpoint for AddRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.songs.add";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = Add<'de>;
    type Response = AddResponse;
}

pub mod add_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Sources;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Sources = Unset;
    }
    ///State transition - sets the `sources` field to Set
    pub struct SetSources<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSources<S> {}
    impl<S: State> State for SetSources<S> {
        type Sources = Set<members::sources>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `sources` field
        pub struct sources(());
    }
}

/// Builder for constructing an instance of this type
pub struct AddBuilder<'a, S: add_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Vec<SongUrlSource<'a>>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Add<'a> {
    /// Create a new builder for this type
    pub fn new() -> AddBuilder<'a, add_state::Empty> {
        AddBuilder::new()
    }
}

impl<'a> AddBuilder<'a, add_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        AddBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> AddBuilder<'a, S>
where
    S: add_state::State,
    S::Sources: add_state::IsUnset,
{
    /// Set the `sources` field (required)
    pub fn sources(
        mut self,
        value: impl Into<Vec<SongUrlSource<'a>>>,
    ) -> AddBuilder<'a, add_state::SetSources<S>> {
        self._fields.0 = Option::Some(value.into());
        AddBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> AddBuilder<'a, S>
where
    S: add_state::State,
    S::Sources: add_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Add<'a> {
        Add {
            sources: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Add<'a> {
        Add {
            sources: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}