// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.songs.cover
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Serialize, Deserialize};
use crate::pet_nkp::radio::Song;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Cover {
    pub body: Bytes,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct CoverOutput<'a> {
    #[serde(borrow)]
    pub song: Song<'a>,
}


#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic
)]

#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum CoverError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "AdminRequired")]
    AdminRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
    #[serde(rename = "SongNotFound")]
    SongNotFound(Option<CowStr<'a>>),
}

impl core::fmt::Display for CoverError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AdminRequired(msg) => {
                write!(f, "AdminRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::SongNotFound(msg) => {
                write!(f, "SongNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for pet.nkp.radio.songs.cover
pub struct CoverResponse;
impl jacquard_common::xrpc::XrpcResp for CoverResponse {
    const NSID: &'static str = "pet.nkp.radio.songs.cover";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = CoverOutput<'de>;
    type Err<'de> = CoverError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for Cover {
    const NSID: &'static str = "pet.nkp.radio.songs.cover";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "multipart/form-data",
    );
    type Response = CoverResponse;
    fn encode_body(&self) -> Result<Vec<u8>, jacquard_common::xrpc::EncodeError> {
        Ok(self.body.to_vec())
    }
    fn decode_body<'de>(
        body: &'de [u8],
    ) -> Result<Box<Self>, jacquard_common::error::DecodeError>
    where
        Self: serde::Deserialize<'de>,
    {
        Ok(
            Box::new(Self {
                body: jacquard_common::deps::bytes::Bytes::copy_from_slice(body),
            }),
        )
    }
}

/// Endpoint type for pet.nkp.radio.songs.cover
pub struct CoverRequest;
impl jacquard_common::xrpc::XrpcEndpoint for CoverRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.songs.cover";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "multipart/form-data",
    );
    type Request<'de> = Cover;
    type Response = CoverResponse;
}