// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.songs.list
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Serialize, Deserialize};
use crate::pet_nkp::radio::Song;

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ListOutput<'a> {
    ///Songs ordered by newest first.
    #[serde(borrow)]
    pub songs: Vec<Song<'a>>,
}


#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic
)]

#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
}

impl core::fmt::Display for ListError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// XRPC request marker type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Copy)]
pub struct List;
/// Response type for pet.nkp.radio.songs.list
pub struct ListResponse;
impl jacquard_common::xrpc::XrpcResp for ListResponse {
    const NSID: &'static str = "pet.nkp.radio.songs.list";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ListOutput<'de>;
    type Err<'de> = ListError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for List {
    const NSID: &'static str = "pet.nkp.radio.songs.list";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListResponse;
}

/// Endpoint type for pet.nkp.radio.songs.list
pub struct ListRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.songs.list";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = List;
    type Response = ListResponse;
}