// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.chat.bans.modify
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Serialize, Deserialize};
use crate::pet_nkp::radio::ChatBan;

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Modify<'a> {
    #[serde(borrow)]
    pub action: ModifyAction<'a>,
    #[serde(borrow)]
    pub did: CowStr<'a>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub reason: Option<CowStr<'a>>,
}


#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ModifyAction<'a> {
    Create,
    Remove,
    Other(CowStr<'a>),
}

impl<'a> ModifyAction<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Create => "create",
            Self::Remove => "remove",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for ModifyAction<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "create" => Self::Create,
            "remove" => Self::Remove,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for ModifyAction<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "create" => Self::Create,
            "remove" => Self::Remove,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for ModifyAction<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for ModifyAction<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for ModifyAction<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for ModifyAction<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for ModifyAction<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for ModifyAction<'_> {
    type Output = ModifyAction<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            ModifyAction::Create => ModifyAction::Create,
            ModifyAction::Remove => ModifyAction::Remove,
            ModifyAction::Other(v) => ModifyAction::Other(v.into_static()),
        }
    }
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct ModifyOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub ban: Option<ChatBan<'a>>,
}


#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic
)]

#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ModifyError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "AdminRequired")]
    AdminRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
    #[serde(rename = "BanNotFound")]
    BanNotFound(Option<CowStr<'a>>),
}

impl core::fmt::Display for ModifyError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AdminRequired(msg) => {
                write!(f, "AdminRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BanNotFound(msg) => {
                write!(f, "BanNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for pet.nkp.radio.chat.bans.modify
pub struct ModifyResponse;
impl jacquard_common::xrpc::XrpcResp for ModifyResponse {
    const NSID: &'static str = "pet.nkp.radio.chat.bans.modify";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ModifyOutput<'de>;
    type Err<'de> = ModifyError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for Modify<'a> {
    const NSID: &'static str = "pet.nkp.radio.chat.bans.modify";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = ModifyResponse;
}

/// Endpoint type for pet.nkp.radio.chat.bans.modify
pub struct ModifyRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ModifyRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.chat.bans.modify";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = Modify<'de>;
    type Response = ModifyResponse;
}