// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.subsonic.import
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::pet_nkp::radio::Song;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::types::string::UriValue;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Deserialize, Serialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Import<'a> {
    /// Defaults to `false`.
    #[serde(default = "_default_import_add_to_queue")]
    pub add_to_queue: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cover_art_id: Option<CowStr<'a>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub password: Option<CowStr<'a>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub server_url: Option<UriValue<'a>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub share_url: Option<UriValue<'a>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub song_id: Option<CowStr<'a>>,
    #[serde(borrow)]
    pub source: ImportSource<'a>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub username: Option<CowStr<'a>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ImportSource<'a> {
    Song,
    Share,
    Other(CowStr<'a>),
}

impl<'a> ImportSource<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Song => "song",
            Self::Share => "share",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for ImportSource<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "song" => Self::Song,
            "share" => Self::Share,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for ImportSource<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "song" => Self::Song,
            "share" => Self::Share,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for ImportSource<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for ImportSource<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for ImportSource<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for ImportSource<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for ImportSource<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for ImportSource<'_> {
    type Output = ImportSource<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            ImportSource::Song => ImportSource::Song,
            ImportSource::Share => ImportSource::Share,
            ImportSource::Other(v) => ImportSource::Other(v.into_static()),
        }
    }
}

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ImportOutput<'a> {
    #[serde(borrow)]
    pub song: Song<'a>,
}

#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic,
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ImportError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "AdminRequired")]
    AdminRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
    #[serde(rename = "SubsonicFailed")]
    SubsonicFailed(Option<CowStr<'a>>),
}

impl core::fmt::Display for ImportError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AdminRequired(msg) => {
                write!(f, "AdminRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::SubsonicFailed(msg) => {
                write!(f, "SubsonicFailed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for pet.nkp.radio.subsonic.import
pub struct ImportResponse;
impl jacquard_common::xrpc::XrpcResp for ImportResponse {
    const NSID: &'static str = "pet.nkp.radio.subsonic.import";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ImportOutput<'de>;
    type Err<'de> = ImportError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for Import<'a> {
    const NSID: &'static str = "pet.nkp.radio.subsonic.import";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = ImportResponse;
}

/// Endpoint type for pet.nkp.radio.subsonic.import
pub struct ImportRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ImportRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.subsonic.import";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<'de> = Import<'de>;
    type Response = ImportResponse;
}

fn _default_import_add_to_queue() -> bool {
    false
}

pub mod import_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type AddToQueue;
        type Source;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type AddToQueue = Unset;
        type Source = Unset;
    }
    ///State transition - sets the `add_to_queue` field to Set
    pub struct SetAddToQueue<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAddToQueue<S> {}
    impl<S: State> State for SetAddToQueue<S> {
        type AddToQueue = Set<members::add_to_queue>;
        type Source = S::Source;
    }
    ///State transition - sets the `source` field to Set
    pub struct SetSource<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSource<S> {}
    impl<S: State> State for SetSource<S> {
        type AddToQueue = S::AddToQueue;
        type Source = Set<members::source>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `add_to_queue` field
        pub struct add_to_queue(());
        ///Marker type for the `source` field
        pub struct source(());
    }
}

/// Builder for constructing an instance of this type
pub struct ImportBuilder<'a, S: import_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<bool>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<UriValue<'a>>,
        Option<UriValue<'a>>,
        Option<CowStr<'a>>,
        Option<ImportSource<'a>>,
        Option<CowStr<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Import<'a> {
    /// Create a new builder for this type
    pub fn new() -> ImportBuilder<'a, import_state::Empty> {
        ImportBuilder::new()
    }
}

impl<'a> ImportBuilder<'a, import_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ImportBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ImportBuilder<'a, S>
where
    S: import_state::State,
    S::AddToQueue: import_state::IsUnset,
{
    /// Set the `addToQueue` field (required)
    pub fn add_to_queue(
        mut self,
        value: impl Into<bool>,
    ) -> ImportBuilder<'a, import_state::SetAddToQueue<S>> {
        self._fields.0 = Option::Some(value.into());
        ImportBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: import_state::State> ImportBuilder<'a, S> {
    /// Set the `coverArtId` field (optional)
    pub fn cover_art_id(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `coverArtId` field to an Option value (optional)
    pub fn maybe_cover_art_id(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S: import_state::State> ImportBuilder<'a, S> {
    /// Set the `password` field (optional)
    pub fn password(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `password` field to an Option value (optional)
    pub fn maybe_password(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<'a, S: import_state::State> ImportBuilder<'a, S> {
    /// Set the `serverUrl` field (optional)
    pub fn server_url(mut self, value: impl Into<Option<UriValue<'a>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `serverUrl` field to an Option value (optional)
    pub fn maybe_server_url(mut self, value: Option<UriValue<'a>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<'a, S: import_state::State> ImportBuilder<'a, S> {
    /// Set the `shareUrl` field (optional)
    pub fn share_url(mut self, value: impl Into<Option<UriValue<'a>>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `shareUrl` field to an Option value (optional)
    pub fn maybe_share_url(mut self, value: Option<UriValue<'a>>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<'a, S: import_state::State> ImportBuilder<'a, S> {
    /// Set the `songId` field (optional)
    pub fn song_id(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `songId` field to an Option value (optional)
    pub fn maybe_song_id(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<'a, S> ImportBuilder<'a, S>
where
    S: import_state::State,
    S::Source: import_state::IsUnset,
{
    /// Set the `source` field (required)
    pub fn source(
        mut self,
        value: impl Into<ImportSource<'a>>,
    ) -> ImportBuilder<'a, import_state::SetSource<S>> {
        self._fields.6 = Option::Some(value.into());
        ImportBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: import_state::State> ImportBuilder<'a, S> {
    /// Set the `username` field (optional)
    pub fn username(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.7 = value.into();
        self
    }
    /// Set the `username` field to an Option value (optional)
    pub fn maybe_username(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.7 = value;
        self
    }
}

impl<'a, S> ImportBuilder<'a, S>
where
    S: import_state::State,
    S::AddToQueue: import_state::IsSet,
    S::Source: import_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Import<'a> {
        Import {
            add_to_queue: self._fields.0.unwrap(),
            cover_art_id: self._fields.1,
            password: self._fields.2,
            server_url: self._fields.3,
            share_url: self._fields.4,
            song_id: self._fields.5,
            source: self._fields.6.unwrap(),
            username: self._fields.7,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Import<'a> {
        Import {
            add_to_queue: self._fields.0.unwrap(),
            cover_art_id: self._fields.1,
            password: self._fields.2,
            server_url: self._fields.3,
            share_url: self._fields.4,
            song_id: self._fields.5,
            source: self._fields.6.unwrap(),
            username: self._fields.7,
            extra_data: Some(extra_data),
        }
    }
}
