// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.subsonic.search
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::pet_nkp::radio::SubsonicSongResult;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::types::string::UriValue;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Deserialize, Serialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Search<'a> {
    #[serde(borrow)]
    pub password: CowStr<'a>,
    #[serde(borrow)]
    pub query: CowStr<'a>,
    #[serde(borrow)]
    pub server_url: UriValue<'a>,
    #[serde(borrow)]
    pub username: CowStr<'a>,
}

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct SearchOutput<'a> {
    #[serde(borrow)]
    pub results: Vec<SubsonicSongResult<'a>>,
}

#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic,
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum SearchError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "AdminRequired")]
    AdminRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
    #[serde(rename = "SubsonicFailed")]
    SubsonicFailed(Option<CowStr<'a>>),
}

impl core::fmt::Display for SearchError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AdminRequired(msg) => {
                write!(f, "AdminRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::SubsonicFailed(msg) => {
                write!(f, "SubsonicFailed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for pet.nkp.radio.subsonic.search
pub struct SearchResponse;
impl jacquard_common::xrpc::XrpcResp for SearchResponse {
    const NSID: &'static str = "pet.nkp.radio.subsonic.search";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = SearchOutput<'de>;
    type Err<'de> = SearchError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for Search<'a> {
    const NSID: &'static str = "pet.nkp.radio.subsonic.search";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = SearchResponse;
}

/// Endpoint type for pet.nkp.radio.subsonic.search
pub struct SearchRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SearchRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.subsonic.search";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<'de> = Search<'de>;
    type Response = SearchResponse;
}

pub mod search_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Query;
        type Username;
        type Password;
        type ServerUrl;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Query = Unset;
        type Username = Unset;
        type Password = Unset;
        type ServerUrl = Unset;
    }
    ///State transition - sets the `query` field to Set
    pub struct SetQuery<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetQuery<S> {}
    impl<S: State> State for SetQuery<S> {
        type Query = Set<members::query>;
        type Username = S::Username;
        type Password = S::Password;
        type ServerUrl = S::ServerUrl;
    }
    ///State transition - sets the `username` field to Set
    pub struct SetUsername<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUsername<S> {}
    impl<S: State> State for SetUsername<S> {
        type Query = S::Query;
        type Username = Set<members::username>;
        type Password = S::Password;
        type ServerUrl = S::ServerUrl;
    }
    ///State transition - sets the `password` field to Set
    pub struct SetPassword<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetPassword<S> {}
    impl<S: State> State for SetPassword<S> {
        type Query = S::Query;
        type Username = S::Username;
        type Password = Set<members::password>;
        type ServerUrl = S::ServerUrl;
    }
    ///State transition - sets the `server_url` field to Set
    pub struct SetServerUrl<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetServerUrl<S> {}
    impl<S: State> State for SetServerUrl<S> {
        type Query = S::Query;
        type Username = S::Username;
        type Password = S::Password;
        type ServerUrl = Set<members::server_url>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `query` field
        pub struct query(());
        ///Marker type for the `username` field
        pub struct username(());
        ///Marker type for the `password` field
        pub struct password(());
        ///Marker type for the `server_url` field
        pub struct server_url(());
    }
}

/// Builder for constructing an instance of this type
pub struct SearchBuilder<'a, S: search_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<UriValue<'a>>,
        Option<CowStr<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Search<'a> {
    /// Create a new builder for this type
    pub fn new() -> SearchBuilder<'a, search_state::Empty> {
        SearchBuilder::new()
    }
}

impl<'a> SearchBuilder<'a, search_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        SearchBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SearchBuilder<'a, S>
where
    S: search_state::State,
    S::Password: search_state::IsUnset,
{
    /// Set the `password` field (required)
    pub fn password(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> SearchBuilder<'a, search_state::SetPassword<S>> {
        self._fields.0 = Option::Some(value.into());
        SearchBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SearchBuilder<'a, S>
where
    S: search_state::State,
    S::Query: search_state::IsUnset,
{
    /// Set the `query` field (required)
    pub fn query(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> SearchBuilder<'a, search_state::SetQuery<S>> {
        self._fields.1 = Option::Some(value.into());
        SearchBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SearchBuilder<'a, S>
where
    S: search_state::State,
    S::ServerUrl: search_state::IsUnset,
{
    /// Set the `serverUrl` field (required)
    pub fn server_url(
        mut self,
        value: impl Into<UriValue<'a>>,
    ) -> SearchBuilder<'a, search_state::SetServerUrl<S>> {
        self._fields.2 = Option::Some(value.into());
        SearchBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SearchBuilder<'a, S>
where
    S: search_state::State,
    S::Username: search_state::IsUnset,
{
    /// Set the `username` field (required)
    pub fn username(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> SearchBuilder<'a, search_state::SetUsername<S>> {
        self._fields.3 = Option::Some(value.into());
        SearchBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SearchBuilder<'a, S>
where
    S: search_state::State,
    S::Query: search_state::IsSet,
    S::Username: search_state::IsSet,
    S::Password: search_state::IsSet,
    S::ServerUrl: search_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Search<'a> {
        Search {
            password: self._fields.0.unwrap(),
            query: self._fields.1.unwrap(),
            server_url: self._fields.2.unwrap(),
            username: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Search<'a> {
        Search {
            password: self._fields.0.unwrap(),
            query: self._fields.1.unwrap(),
            server_url: self._fields.2.unwrap(),
            username: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}
