// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.control
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::pet_nkp::radio::RadioSnapshot;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Deserialize, Serialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Control<'a> {
    #[serde(borrow)]
    pub action: ControlAction<'a>,
    #[serde(borrow)]
    pub intent: ControlIntent<'a>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ControlAction<'a> {
    Play,
    Pause,
    Stop,
    Skip,
    Previous,
    Other(CowStr<'a>),
}

impl<'a> ControlAction<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Play => "play",
            Self::Pause => "pause",
            Self::Stop => "stop",
            Self::Skip => "skip",
            Self::Previous => "previous",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for ControlAction<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "play" => Self::Play,
            "pause" => Self::Pause,
            "stop" => Self::Stop,
            "skip" => Self::Skip,
            "previous" => Self::Previous,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for ControlAction<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "play" => Self::Play,
            "pause" => Self::Pause,
            "stop" => Self::Stop,
            "skip" => Self::Skip,
            "previous" => Self::Previous,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for ControlAction<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for ControlAction<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for ControlAction<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for ControlAction<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for ControlAction<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for ControlAction<'_> {
    type Output = ControlAction<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            ControlAction::Play => ControlAction::Play,
            ControlAction::Pause => ControlAction::Pause,
            ControlAction::Stop => ControlAction::Stop,
            ControlAction::Skip => ControlAction::Skip,
            ControlAction::Previous => ControlAction::Previous,
            ControlAction::Other(v) => ControlAction::Other(v.into_static()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ControlIntent<'a> {
    ExplicitAdminAction,
    Other(CowStr<'a>),
}

impl<'a> ControlIntent<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::ExplicitAdminAction => "explicit_admin_action",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for ControlIntent<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "explicit_admin_action" => Self::ExplicitAdminAction,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for ControlIntent<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "explicit_admin_action" => Self::ExplicitAdminAction,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for ControlIntent<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for ControlIntent<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for ControlIntent<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for ControlIntent<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for ControlIntent<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for ControlIntent<'_> {
    type Output = ControlIntent<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            ControlIntent::ExplicitAdminAction => ControlIntent::ExplicitAdminAction,
            ControlIntent::Other(v) => ControlIntent::Other(v.into_static()),
        }
    }
}

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ControlOutput<'a> {
    #[serde(borrow)]
    pub snapshot: RadioSnapshot<'a>,
}

#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic,
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ControlError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "AdminRequired")]
    AdminRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
}

impl core::fmt::Display for ControlError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AdminRequired(msg) => {
                write!(f, "AdminRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for pet.nkp.radio.control
pub struct ControlResponse;
impl jacquard_common::xrpc::XrpcResp for ControlResponse {
    const NSID: &'static str = "pet.nkp.radio.control";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ControlOutput<'de>;
    type Err<'de> = ControlError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for Control<'a> {
    const NSID: &'static str = "pet.nkp.radio.control";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = ControlResponse;
}

/// Endpoint type for pet.nkp.radio.control
pub struct ControlRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ControlRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.control";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<'de> = Control<'de>;
    type Response = ControlResponse;
}
