// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.preferences
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// A singleton preference record for radio UI settings. Volume intentionally stays browser-local.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "pet.nkp.radio.preferences",
    tag = "$type"
)]
pub struct Preferences<'a> {
    ///Preferred accent color token or CSS color value.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub accent_color: Option<CowStr<'a>>,
    ///Preferred theme mode.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub theme: Option<PreferencesTheme<'a>>,
    ///Client-declared timestamp when preferences were last updated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Datetime>,
}

/// Preferred theme mode.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PreferencesTheme<'a> {
    Light,
    Dark,
    System,
    Other(CowStr<'a>),
}

impl<'a> PreferencesTheme<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Light => "light",
            Self::Dark => "dark",
            Self::System => "system",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for PreferencesTheme<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "light" => Self::Light,
            "dark" => Self::Dark,
            "system" => Self::System,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for PreferencesTheme<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "light" => Self::Light,
            "dark" => Self::Dark,
            "system" => Self::System,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for PreferencesTheme<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for PreferencesTheme<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for PreferencesTheme<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for PreferencesTheme<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for PreferencesTheme<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for PreferencesTheme<'_> {
    type Output = PreferencesTheme<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            PreferencesTheme::Light => PreferencesTheme::Light,
            PreferencesTheme::Dark => PreferencesTheme::Dark,
            PreferencesTheme::System => PreferencesTheme::System,
            PreferencesTheme::Other(v) => PreferencesTheme::Other(v.into_static()),
        }
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct PreferencesGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Preferences<'a>,
}

impl<'a> Preferences<'a> {
    pub fn uri(uri: impl Into<CowStr<'a>>) -> Result<RecordUri<'a, PreferencesRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct PreferencesRecord;
impl XrpcResp for PreferencesRecord {
    const NSID: &'static str = "pet.nkp.radio.preferences";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = PreferencesGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<PreferencesGetRecordOutput<'_>> for Preferences<'_> {
    fn from(output: PreferencesGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Preferences<'_> {
    const NSID: &'static str = "pet.nkp.radio.preferences";
    type Record = PreferencesRecord;
}

impl Collection for PreferencesRecord {
    const NSID: &'static str = "pet.nkp.radio.preferences";
    type Record = PreferencesRecord;
}

impl<'a> LexiconSchema for Preferences<'a> {
    fn nsid() -> &'static str {
        "pet.nkp.radio.preferences"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_pet_nkp_radio_preferences()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        if let Some(ref value) = self.accent_color {
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 64usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("accent_color"),
                    max: 64usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod preferences_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct PreferencesBuilder<'a, S: preferences_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<CowStr<'a>>,
        Option<PreferencesTheme<'a>>,
        Option<Datetime>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Preferences<'a> {
    /// Create a new builder for this type
    pub fn new() -> PreferencesBuilder<'a, preferences_state::Empty> {
        PreferencesBuilder::new()
    }
}

impl<'a> PreferencesBuilder<'a, preferences_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PreferencesBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: preferences_state::State> PreferencesBuilder<'a, S> {
    /// Set the `accentColor` field (optional)
    pub fn accent_color(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `accentColor` field to an Option value (optional)
    pub fn maybe_accent_color(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<'a, S: preferences_state::State> PreferencesBuilder<'a, S> {
    /// Set the `theme` field (optional)
    pub fn theme(mut self, value: impl Into<Option<PreferencesTheme<'a>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `theme` field to an Option value (optional)
    pub fn maybe_theme(mut self, value: Option<PreferencesTheme<'a>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S: preferences_state::State> PreferencesBuilder<'a, S> {
    /// Set the `updatedAt` field (optional)
    pub fn updated_at(mut self, value: impl Into<Option<Datetime>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `updatedAt` field to an Option value (optional)
    pub fn maybe_updated_at(mut self, value: Option<Datetime>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<'a, S> PreferencesBuilder<'a, S>
where
    S: preferences_state::State,
{
    /// Build the final struct
    pub fn build(self) -> Preferences<'a> {
        Preferences {
            accent_color: self._fields.0,
            theme: self._fields.1,
            updated_at: self._fields.2,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Preferences<'a> {
        Preferences {
            accent_color: self._fields.0,
            theme: self._fields.1,
            updated_at: self._fields.2,
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_pet_nkp_radio_preferences() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("pet.nkp.radio.preferences"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A singleton preference record for radio UI settings. Volume intentionally stays browser-local.",
                        ),
                    ),
                    key: Some(CowStr::new_static("literal:self")),
                    record: LexRecordRecord::Object(LexObject {
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("accentColor"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Preferred accent color token or CSS color value.",
                                        ),
                                    ),
                                    max_length: Some(64usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("theme"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static("Preferred theme mode."),
                                    ),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("updatedAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Client-declared timestamp when preferences were last updated.",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
