// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

pub mod preferences;
pub mod queue;
pub mod songs;

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::string::UriValue;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

use crate::pet_nkp::radio;
#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};
/// Queue item joined with song metadata.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct QueueItem<'a> {
    ///DID that originally uploaded the queued song.
    #[serde(borrow)]
    pub added_by_did: CowStr<'a>,
    ///Optional queued song album.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub album: Option<CowStr<'a>>,
    ///Queued song artist.
    #[serde(borrow)]
    pub artist: CowStr<'a>,
    ///Optional queued song duration in seconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<i64>,
    ///Stable queue item id.
    #[serde(borrow)]
    pub id: CowStr<'a>,
    ///Queue position, lower values play first.
    pub position: i64,
    ///DID that queued the song.
    #[serde(borrow)]
    pub queued_by_did: CowStr<'a>,
    ///Full metadata for the queued song.
    #[serde(borrow)]
    pub song: radio::Song<'a>,
    ///Queued song id.
    #[serde(borrow)]
    pub song_id: CowStr<'a>,
    ///Queued song title.
    #[serde(borrow)]
    pub title: CowStr<'a>,
}

/// Combined radio view returned to clients.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RadioSnapshot<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub current_song: Option<radio::Song<'a>>,
    ///Compatibility alias for the current song.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub now_playing: Option<radio::Song<'a>>,
    ///Upcoming queued songs.
    #[serde(borrow)]
    pub queue: Vec<radio::QueueItem<'a>>,
    #[serde(borrow)]
    pub state: radio::RadioState<'a>,
}

/// Radio playback status persisted by the backend.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct RadioState<'a> {
    ///Currently active song id, when one is selected.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub current_song_id: Option<CowStr<'a>>,
    ///Unix timestamp when playback was last paused.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paused_at: Option<i64>,
    ///Stored playback offset in seconds.
    pub position_seconds: i64,
    ///Unix timestamp when playback was last started.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<i64>,
    ///Current playback status.
    #[serde(borrow)]
    pub status: RadioStateStatus<'a>,
    ///DID or backend actor that last updated radio state.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub updated_by_did: Option<CowStr<'a>>,
}

/// Current playback status.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum RadioStateStatus<'a> {
    Playing,
    Paused,
    Stopped,
    Other(CowStr<'a>),
}

impl<'a> RadioStateStatus<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Playing => "playing",
            Self::Paused => "paused",
            Self::Stopped => "stopped",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for RadioStateStatus<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "playing" => Self::Playing,
            "paused" => Self::Paused,
            "stopped" => Self::Stopped,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for RadioStateStatus<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "playing" => Self::Playing,
            "paused" => Self::Paused,
            "stopped" => Self::Stopped,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for RadioStateStatus<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for RadioStateStatus<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for RadioStateStatus<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for RadioStateStatus<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for RadioStateStatus<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for RadioStateStatus<'_> {
    type Output = RadioStateStatus<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            RadioStateStatus::Playing => RadioStateStatus::Playing,
            RadioStateStatus::Paused => RadioStateStatus::Paused,
            RadioStateStatus::Stopped => RadioStateStatus::Stopped,
            RadioStateStatus::Other(v) => RadioStateStatus::Other(v.into_static()),
        }
    }
}

/// Song metadata stored by the radio backend.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct Song<'a> {
    ///DID that uploaded the song.
    #[serde(borrow)]
    pub added_by_did: CowStr<'a>,
    ///Optional album title.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub album: Option<CowStr<'a>>,
    ///Song artist.
    #[serde(borrow)]
    pub artist: CowStr<'a>,
    ///Unix timestamp when the song was uploaded.
    pub created_at: i64,
    ///Optional duration in seconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<i64>,
    ///Optional genre.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub genre: Option<CowStr<'a>>,
    ///Whether the song has cover art.
    pub has_cover: bool,
    ///Stable song id.
    #[serde(borrow)]
    pub id: CowStr<'a>,
    ///Integrated loudness in LUFS, serialized as a decimal string.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub loudness_lufs: Option<CowStr<'a>>,
    ///True peak in dBFS, serialized as a decimal string.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub loudness_peak: Option<CowStr<'a>>,
    ///Stored audio MIME type.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub mime_type: Option<CowStr<'a>>,
    ///Song title.
    #[serde(borrow)]
    pub title: CowStr<'a>,
}

/// Remote audio source to import through the existing backend URL importer.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct SongUrlSource<'a> {
    ///Whether imported songs should be queued immediately.  Defaults to `false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default = "_default_song_url_source_add_to_queue")]
    pub add_to_queue: Option<bool>,
    ///Optional album override.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub album: Option<CowStr<'a>>,
    ///Optional artist override for plain audio URLs.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub artist: Option<CowStr<'a>>,
    ///Optional title override for plain audio URLs.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub title: Option<CowStr<'a>>,
    ///HTTP(S) audio, playlist, or yt-dlp-supported URL to import.
    #[serde(borrow)]
    pub url: UriValue<'a>,
}

impl<'a> LexiconSchema for QueueItem<'a> {
    fn nsid() -> &'static str {
        "pet.nkp.radio"
    }
    fn def_name() -> &'static str {
        "queueItem"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_pet_nkp_radio()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.artist;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 512usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("artist"),
                    max: 512usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.artist;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("artist"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 128usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("id"),
                    max: 128usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("id"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.position;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("position"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.song_id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 128usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("song_id"),
                    max: 128usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.song_id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("song_id"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 512usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("title"),
                    max: 512usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("title"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for RadioSnapshot<'a> {
    fn nsid() -> &'static str {
        "pet.nkp.radio"
    }
    fn def_name() -> &'static str {
        "radioSnapshot"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_pet_nkp_radio()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for RadioState<'a> {
    fn nsid() -> &'static str {
        "pet.nkp.radio"
    }
    fn def_name() -> &'static str {
        "radioState"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_pet_nkp_radio()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.position_seconds;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("position_seconds"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for Song<'a> {
    fn nsid() -> &'static str {
        "pet.nkp.radio"
    }
    fn def_name() -> &'static str {
        "song"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_pet_nkp_radio()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.artist;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 512usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("artist"),
                    max: 512usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.artist;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("artist"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.created_at;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("created_at"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 128usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("id"),
                    max: 128usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.id;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("id"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 512usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("title"),
                    max: 512usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.title;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("title"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

impl<'a> LexiconSchema for SongUrlSource<'a> {
    fn nsid() -> &'static str {
        "pet.nkp.radio"
    }
    fn def_name() -> &'static str {
        "songUrlSource"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_pet_nkp_radio()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.url;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 4096usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("url"),
                    max: 4096usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.url;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 8usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("url"),
                    min: 8usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        Ok(())
    }
}

pub mod queue_item_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Song;
        type AddedByDid;
        type QueuedByDid;
        type Title;
        type Id;
        type SongId;
        type Artist;
        type Position;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Song = Unset;
        type AddedByDid = Unset;
        type QueuedByDid = Unset;
        type Title = Unset;
        type Id = Unset;
        type SongId = Unset;
        type Artist = Unset;
        type Position = Unset;
    }
    ///State transition - sets the `song` field to Set
    pub struct SetSong<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSong<S> {}
    impl<S: State> State for SetSong<S> {
        type Song = Set<members::song>;
        type AddedByDid = S::AddedByDid;
        type QueuedByDid = S::QueuedByDid;
        type Title = S::Title;
        type Id = S::Id;
        type SongId = S::SongId;
        type Artist = S::Artist;
        type Position = S::Position;
    }
    ///State transition - sets the `added_by_did` field to Set
    pub struct SetAddedByDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAddedByDid<S> {}
    impl<S: State> State for SetAddedByDid<S> {
        type Song = S::Song;
        type AddedByDid = Set<members::added_by_did>;
        type QueuedByDid = S::QueuedByDid;
        type Title = S::Title;
        type Id = S::Id;
        type SongId = S::SongId;
        type Artist = S::Artist;
        type Position = S::Position;
    }
    ///State transition - sets the `queued_by_did` field to Set
    pub struct SetQueuedByDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetQueuedByDid<S> {}
    impl<S: State> State for SetQueuedByDid<S> {
        type Song = S::Song;
        type AddedByDid = S::AddedByDid;
        type QueuedByDid = Set<members::queued_by_did>;
        type Title = S::Title;
        type Id = S::Id;
        type SongId = S::SongId;
        type Artist = S::Artist;
        type Position = S::Position;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTitle<S> {}
    impl<S: State> State for SetTitle<S> {
        type Song = S::Song;
        type AddedByDid = S::AddedByDid;
        type QueuedByDid = S::QueuedByDid;
        type Title = Set<members::title>;
        type Id = S::Id;
        type SongId = S::SongId;
        type Artist = S::Artist;
        type Position = S::Position;
    }
    ///State transition - sets the `id` field to Set
    pub struct SetId<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetId<S> {}
    impl<S: State> State for SetId<S> {
        type Song = S::Song;
        type AddedByDid = S::AddedByDid;
        type QueuedByDid = S::QueuedByDid;
        type Title = S::Title;
        type Id = Set<members::id>;
        type SongId = S::SongId;
        type Artist = S::Artist;
        type Position = S::Position;
    }
    ///State transition - sets the `song_id` field to Set
    pub struct SetSongId<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSongId<S> {}
    impl<S: State> State for SetSongId<S> {
        type Song = S::Song;
        type AddedByDid = S::AddedByDid;
        type QueuedByDid = S::QueuedByDid;
        type Title = S::Title;
        type Id = S::Id;
        type SongId = Set<members::song_id>;
        type Artist = S::Artist;
        type Position = S::Position;
    }
    ///State transition - sets the `artist` field to Set
    pub struct SetArtist<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetArtist<S> {}
    impl<S: State> State for SetArtist<S> {
        type Song = S::Song;
        type AddedByDid = S::AddedByDid;
        type QueuedByDid = S::QueuedByDid;
        type Title = S::Title;
        type Id = S::Id;
        type SongId = S::SongId;
        type Artist = Set<members::artist>;
        type Position = S::Position;
    }
    ///State transition - sets the `position` field to Set
    pub struct SetPosition<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetPosition<S> {}
    impl<S: State> State for SetPosition<S> {
        type Song = S::Song;
        type AddedByDid = S::AddedByDid;
        type QueuedByDid = S::QueuedByDid;
        type Title = S::Title;
        type Id = S::Id;
        type SongId = S::SongId;
        type Artist = S::Artist;
        type Position = Set<members::position>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `song` field
        pub struct song(());
        ///Marker type for the `added_by_did` field
        pub struct added_by_did(());
        ///Marker type for the `queued_by_did` field
        pub struct queued_by_did(());
        ///Marker type for the `title` field
        pub struct title(());
        ///Marker type for the `id` field
        pub struct id(());
        ///Marker type for the `song_id` field
        pub struct song_id(());
        ///Marker type for the `artist` field
        pub struct artist(());
        ///Marker type for the `position` field
        pub struct position(());
    }
}

/// Builder for constructing an instance of this type
pub struct QueueItemBuilder<'a, S: queue_item_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<i64>,
        Option<CowStr<'a>>,
        Option<i64>,
        Option<CowStr<'a>>,
        Option<radio::Song<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> QueueItem<'a> {
    /// Create a new builder for this type
    pub fn new() -> QueueItemBuilder<'a, queue_item_state::Empty> {
        QueueItemBuilder::new()
    }
}

impl<'a> QueueItemBuilder<'a, queue_item_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        QueueItemBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::AddedByDid: queue_item_state::IsUnset,
{
    /// Set the `addedByDid` field (required)
    pub fn added_by_did(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetAddedByDid<S>> {
        self._fields.0 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: queue_item_state::State> QueueItemBuilder<'a, S> {
    /// Set the `album` field (optional)
    pub fn album(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `album` field to an Option value (optional)
    pub fn maybe_album(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::Artist: queue_item_state::IsUnset,
{
    /// Set the `artist` field (required)
    pub fn artist(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetArtist<S>> {
        self._fields.2 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: queue_item_state::State> QueueItemBuilder<'a, S> {
    /// Set the `durationSeconds` field (optional)
    pub fn duration_seconds(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `durationSeconds` field to an Option value (optional)
    pub fn maybe_duration_seconds(mut self, value: Option<i64>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::Id: queue_item_state::IsUnset,
{
    /// Set the `id` field (required)
    pub fn id(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetId<S>> {
        self._fields.4 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::Position: queue_item_state::IsUnset,
{
    /// Set the `position` field (required)
    pub fn position(
        mut self,
        value: impl Into<i64>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetPosition<S>> {
        self._fields.5 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::QueuedByDid: queue_item_state::IsUnset,
{
    /// Set the `queuedByDid` field (required)
    pub fn queued_by_did(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetQueuedByDid<S>> {
        self._fields.6 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::Song: queue_item_state::IsUnset,
{
    /// Set the `song` field (required)
    pub fn song(
        mut self,
        value: impl Into<radio::Song<'a>>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetSong<S>> {
        self._fields.7 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::SongId: queue_item_state::IsUnset,
{
    /// Set the `songId` field (required)
    pub fn song_id(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetSongId<S>> {
        self._fields.8 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::Title: queue_item_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> QueueItemBuilder<'a, queue_item_state::SetTitle<S>> {
        self._fields.9 = Option::Some(value.into());
        QueueItemBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> QueueItemBuilder<'a, S>
where
    S: queue_item_state::State,
    S::Song: queue_item_state::IsSet,
    S::AddedByDid: queue_item_state::IsSet,
    S::QueuedByDid: queue_item_state::IsSet,
    S::Title: queue_item_state::IsSet,
    S::Id: queue_item_state::IsSet,
    S::SongId: queue_item_state::IsSet,
    S::Artist: queue_item_state::IsSet,
    S::Position: queue_item_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> QueueItem<'a> {
        QueueItem {
            added_by_did: self._fields.0.unwrap(),
            album: self._fields.1,
            artist: self._fields.2.unwrap(),
            duration_seconds: self._fields.3,
            id: self._fields.4.unwrap(),
            position: self._fields.5.unwrap(),
            queued_by_did: self._fields.6.unwrap(),
            song: self._fields.7.unwrap(),
            song_id: self._fields.8.unwrap(),
            title: self._fields.9.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> QueueItem<'a> {
        QueueItem {
            added_by_did: self._fields.0.unwrap(),
            album: self._fields.1,
            artist: self._fields.2.unwrap(),
            duration_seconds: self._fields.3,
            id: self._fields.4.unwrap(),
            position: self._fields.5.unwrap(),
            queued_by_did: self._fields.6.unwrap(),
            song: self._fields.7.unwrap(),
            song_id: self._fields.8.unwrap(),
            title: self._fields.9.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_pet_nkp_radio() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("pet.nkp.radio"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("queueItem"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static("Queue item joined with song metadata.")),
                    required: Some(vec![
                        SmolStr::new_static("id"),
                        SmolStr::new_static("position"),
                        SmolStr::new_static("queuedByDid"),
                        SmolStr::new_static("songId"),
                        SmolStr::new_static("song"),
                        SmolStr::new_static("title"),
                        SmolStr::new_static("artist"),
                        SmolStr::new_static("album"),
                        SmolStr::new_static("durationSeconds"),
                        SmolStr::new_static("addedByDid"),
                    ]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("addedByDid"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "DID that originally uploaded the queued song.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("album"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "Optional queued song album.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("artist"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Queued song artist.")),
                                min_length: Some(1usize),
                                max_length: Some(512usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("durationSeconds"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("id"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Stable queue item id.")),
                                min_length: Some(1usize),
                                max_length: Some(128usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("position"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(1i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("queuedByDid"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("DID that queued the song.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("song"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("#song"),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("songId"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Queued song id.")),
                                min_length: Some(1usize),
                                max_length: Some(128usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("title"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Queued song title.")),
                                min_length: Some(1usize),
                                max_length: Some(512usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("radioSnapshot"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Combined radio view returned to clients.",
                    )),
                    required: Some(vec![
                        SmolStr::new_static("state"),
                        SmolStr::new_static("currentSong"),
                        SmolStr::new_static("queue"),
                    ]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("currentSong"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("#song"),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("nowPlaying"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("#song"),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("queue"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(CowStr::new_static("Upcoming queued songs.")),
                                items: LexArrayItem::Ref(LexRef {
                                    r#ref: CowStr::new_static("#queueItem"),
                                    ..Default::default()
                                }),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("state"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("#radioState"),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("radioState"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Radio playback status persisted by the backend.",
                    )),
                    required: Some(vec![
                        SmolStr::new_static("currentSongId"),
                        SmolStr::new_static("status"),
                        SmolStr::new_static("startedAt"),
                        SmolStr::new_static("pausedAt"),
                        SmolStr::new_static("positionSeconds"),
                        SmolStr::new_static("updatedByDid"),
                    ]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("currentSongId"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "Currently active song id, when one is selected.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("pausedAt"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("positionSeconds"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("startedAt"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("status"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Current playback status.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("updatedByDid"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "DID or backend actor that last updated radio state.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("song"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Song metadata stored by the radio backend.",
                    )),
                    required: Some(vec![
                        SmolStr::new_static("id"),
                        SmolStr::new_static("title"),
                        SmolStr::new_static("artist"),
                        SmolStr::new_static("album"),
                        SmolStr::new_static("genre"),
                        SmolStr::new_static("durationSeconds"),
                        SmolStr::new_static("mimeType"),
                        SmolStr::new_static("hasCover"),
                        SmolStr::new_static("addedByDid"),
                        SmolStr::new_static("createdAt"),
                        SmolStr::new_static("loudnessLufs"),
                        SmolStr::new_static("loudnessPeak"),
                    ]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("addedByDid"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "DID that uploaded the song.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("album"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Optional album title.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("artist"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Song artist.")),
                                min_length: Some(1usize),
                                max_length: Some(512usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("createdAt"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("durationSeconds"),
                            LexObjectProperty::Integer(LexInteger {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("genre"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Optional genre.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("hasCover"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("id"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Stable song id.")),
                                min_length: Some(1usize),
                                max_length: Some(128usize),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("loudnessLufs"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "Integrated loudness in LUFS, serialized as a decimal string.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("loudnessPeak"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "True peak in dBFS, serialized as a decimal string.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("mimeType"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Stored audio MIME type.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("title"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Song title.")),
                                min_length: Some(1usize),
                                max_length: Some(512usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("songUrlSource"),
                LexUserType::Object(LexObject {
                    description: Some(CowStr::new_static(
                        "Remote audio source to import through the existing backend URL importer.",
                    )),
                    required: Some(vec![SmolStr::new_static("url")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("addToQueue"),
                            LexObjectProperty::Boolean(LexBoolean {
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("album"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static("Optional album override.")),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("artist"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "Optional artist override for plain audio URLs.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("title"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "Optional title override for plain audio URLs.",
                                )),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("url"),
                            LexObjectProperty::String(LexString {
                                description: Some(CowStr::new_static(
                                    "HTTP(S) audio, playlist, or yt-dlp-supported URL to import.",
                                )),
                                format: Some(LexStringFormat::Uri),
                                min_length: Some(8usize),
                                max_length: Some(4096usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod radio_snapshot_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Queue;
        type State;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Queue = Unset;
        type State = Unset;
    }
    ///State transition - sets the `queue` field to Set
    pub struct SetQueue<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetQueue<S> {}
    impl<S: State> State for SetQueue<S> {
        type Queue = Set<members::queue>;
        type State = S::State;
    }
    ///State transition - sets the `state` field to Set
    pub struct SetState<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetState<S> {}
    impl<S: State> State for SetState<S> {
        type Queue = S::Queue;
        type State = Set<members::state>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `queue` field
        pub struct queue(());
        ///Marker type for the `state` field
        pub struct state(());
    }
}

/// Builder for constructing an instance of this type
pub struct RadioSnapshotBuilder<'a, S: radio_snapshot_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<radio::Song<'a>>,
        Option<radio::Song<'a>>,
        Option<Vec<radio::QueueItem<'a>>>,
        Option<radio::RadioState<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> RadioSnapshot<'a> {
    /// Create a new builder for this type
    pub fn new() -> RadioSnapshotBuilder<'a, radio_snapshot_state::Empty> {
        RadioSnapshotBuilder::new()
    }
}

impl<'a> RadioSnapshotBuilder<'a, radio_snapshot_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RadioSnapshotBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: radio_snapshot_state::State> RadioSnapshotBuilder<'a, S> {
    /// Set the `currentSong` field (optional)
    pub fn current_song(mut self, value: impl Into<Option<radio::Song<'a>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `currentSong` field to an Option value (optional)
    pub fn maybe_current_song(mut self, value: Option<radio::Song<'a>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<'a, S: radio_snapshot_state::State> RadioSnapshotBuilder<'a, S> {
    /// Set the `nowPlaying` field (optional)
    pub fn now_playing(mut self, value: impl Into<Option<radio::Song<'a>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `nowPlaying` field to an Option value (optional)
    pub fn maybe_now_playing(mut self, value: Option<radio::Song<'a>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S> RadioSnapshotBuilder<'a, S>
where
    S: radio_snapshot_state::State,
    S::Queue: radio_snapshot_state::IsUnset,
{
    /// Set the `queue` field (required)
    pub fn queue(
        mut self,
        value: impl Into<Vec<radio::QueueItem<'a>>>,
    ) -> RadioSnapshotBuilder<'a, radio_snapshot_state::SetQueue<S>> {
        self._fields.2 = Option::Some(value.into());
        RadioSnapshotBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RadioSnapshotBuilder<'a, S>
where
    S: radio_snapshot_state::State,
    S::State: radio_snapshot_state::IsUnset,
{
    /// Set the `state` field (required)
    pub fn state(
        mut self,
        value: impl Into<radio::RadioState<'a>>,
    ) -> RadioSnapshotBuilder<'a, radio_snapshot_state::SetState<S>> {
        self._fields.3 = Option::Some(value.into());
        RadioSnapshotBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> RadioSnapshotBuilder<'a, S>
where
    S: radio_snapshot_state::State,
    S::Queue: radio_snapshot_state::IsSet,
    S::State: radio_snapshot_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RadioSnapshot<'a> {
        RadioSnapshot {
            current_song: self._fields.0,
            now_playing: self._fields.1,
            queue: self._fields.2.unwrap(),
            state: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> RadioSnapshot<'a> {
        RadioSnapshot {
            current_song: self._fields.0,
            now_playing: self._fields.1,
            queue: self._fields.2.unwrap(),
            state: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod radio_state_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type PositionSeconds;
        type Status;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type PositionSeconds = Unset;
        type Status = Unset;
    }
    ///State transition - sets the `position_seconds` field to Set
    pub struct SetPositionSeconds<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetPositionSeconds<S> {}
    impl<S: State> State for SetPositionSeconds<S> {
        type PositionSeconds = Set<members::position_seconds>;
        type Status = S::Status;
    }
    ///State transition - sets the `status` field to Set
    pub struct SetStatus<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetStatus<S> {}
    impl<S: State> State for SetStatus<S> {
        type PositionSeconds = S::PositionSeconds;
        type Status = Set<members::status>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `position_seconds` field
        pub struct position_seconds(());
        ///Marker type for the `status` field
        pub struct status(());
    }
}

/// Builder for constructing an instance of this type
pub struct RadioStateBuilder<'a, S: radio_state_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<CowStr<'a>>,
        Option<i64>,
        Option<i64>,
        Option<i64>,
        Option<RadioStateStatus<'a>>,
        Option<CowStr<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> RadioState<'a> {
    /// Create a new builder for this type
    pub fn new() -> RadioStateBuilder<'a, radio_state_state::Empty> {
        RadioStateBuilder::new()
    }
}

impl<'a> RadioStateBuilder<'a, radio_state_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        RadioStateBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: radio_state_state::State> RadioStateBuilder<'a, S> {
    /// Set the `currentSongId` field (optional)
    pub fn current_song_id(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `currentSongId` field to an Option value (optional)
    pub fn maybe_current_song_id(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<'a, S: radio_state_state::State> RadioStateBuilder<'a, S> {
    /// Set the `pausedAt` field (optional)
    pub fn paused_at(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `pausedAt` field to an Option value (optional)
    pub fn maybe_paused_at(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S> RadioStateBuilder<'a, S>
where
    S: radio_state_state::State,
    S::PositionSeconds: radio_state_state::IsUnset,
{
    /// Set the `positionSeconds` field (required)
    pub fn position_seconds(
        mut self,
        value: impl Into<i64>,
    ) -> RadioStateBuilder<'a, radio_state_state::SetPositionSeconds<S>> {
        self._fields.2 = Option::Some(value.into());
        RadioStateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: radio_state_state::State> RadioStateBuilder<'a, S> {
    /// Set the `startedAt` field (optional)
    pub fn started_at(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `startedAt` field to an Option value (optional)
    pub fn maybe_started_at(mut self, value: Option<i64>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<'a, S> RadioStateBuilder<'a, S>
where
    S: radio_state_state::State,
    S::Status: radio_state_state::IsUnset,
{
    /// Set the `status` field (required)
    pub fn status(
        mut self,
        value: impl Into<RadioStateStatus<'a>>,
    ) -> RadioStateBuilder<'a, radio_state_state::SetStatus<S>> {
        self._fields.4 = Option::Some(value.into());
        RadioStateBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: radio_state_state::State> RadioStateBuilder<'a, S> {
    /// Set the `updatedByDid` field (optional)
    pub fn updated_by_did(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `updatedByDid` field to an Option value (optional)
    pub fn maybe_updated_by_did(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<'a, S> RadioStateBuilder<'a, S>
where
    S: radio_state_state::State,
    S::PositionSeconds: radio_state_state::IsSet,
    S::Status: radio_state_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> RadioState<'a> {
        RadioState {
            current_song_id: self._fields.0,
            paused_at: self._fields.1,
            position_seconds: self._fields.2.unwrap(),
            started_at: self._fields.3,
            status: self._fields.4.unwrap(),
            updated_by_did: self._fields.5,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> RadioState<'a> {
        RadioState {
            current_song_id: self._fields.0,
            paused_at: self._fields.1,
            position_seconds: self._fields.2.unwrap(),
            started_at: self._fields.3,
            status: self._fields.4.unwrap(),
            updated_by_did: self._fields.5,
            extra_data: Some(extra_data),
        }
    }
}

pub mod song_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type HasCover;
        type CreatedAt;
        type Id;
        type Artist;
        type Title;
        type AddedByDid;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type HasCover = Unset;
        type CreatedAt = Unset;
        type Id = Unset;
        type Artist = Unset;
        type Title = Unset;
        type AddedByDid = Unset;
    }
    ///State transition - sets the `has_cover` field to Set
    pub struct SetHasCover<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetHasCover<S> {}
    impl<S: State> State for SetHasCover<S> {
        type HasCover = Set<members::has_cover>;
        type CreatedAt = S::CreatedAt;
        type Id = S::Id;
        type Artist = S::Artist;
        type Title = S::Title;
        type AddedByDid = S::AddedByDid;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type HasCover = S::HasCover;
        type CreatedAt = Set<members::created_at>;
        type Id = S::Id;
        type Artist = S::Artist;
        type Title = S::Title;
        type AddedByDid = S::AddedByDid;
    }
    ///State transition - sets the `id` field to Set
    pub struct SetId<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetId<S> {}
    impl<S: State> State for SetId<S> {
        type HasCover = S::HasCover;
        type CreatedAt = S::CreatedAt;
        type Id = Set<members::id>;
        type Artist = S::Artist;
        type Title = S::Title;
        type AddedByDid = S::AddedByDid;
    }
    ///State transition - sets the `artist` field to Set
    pub struct SetArtist<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetArtist<S> {}
    impl<S: State> State for SetArtist<S> {
        type HasCover = S::HasCover;
        type CreatedAt = S::CreatedAt;
        type Id = S::Id;
        type Artist = Set<members::artist>;
        type Title = S::Title;
        type AddedByDid = S::AddedByDid;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetTitle<S> {}
    impl<S: State> State for SetTitle<S> {
        type HasCover = S::HasCover;
        type CreatedAt = S::CreatedAt;
        type Id = S::Id;
        type Artist = S::Artist;
        type Title = Set<members::title>;
        type AddedByDid = S::AddedByDid;
    }
    ///State transition - sets the `added_by_did` field to Set
    pub struct SetAddedByDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetAddedByDid<S> {}
    impl<S: State> State for SetAddedByDid<S> {
        type HasCover = S::HasCover;
        type CreatedAt = S::CreatedAt;
        type Id = S::Id;
        type Artist = S::Artist;
        type Title = S::Title;
        type AddedByDid = Set<members::added_by_did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `has_cover` field
        pub struct has_cover(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `id` field
        pub struct id(());
        ///Marker type for the `artist` field
        pub struct artist(());
        ///Marker type for the `title` field
        pub struct title(());
        ///Marker type for the `added_by_did` field
        pub struct added_by_did(());
    }
}

/// Builder for constructing an instance of this type
pub struct SongBuilder<'a, S: song_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<i64>,
        Option<i64>,
        Option<CowStr<'a>>,
        Option<bool>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Song<'a> {
    /// Create a new builder for this type
    pub fn new() -> SongBuilder<'a, song_state::Empty> {
        SongBuilder::new()
    }
}

impl<'a> SongBuilder<'a, song_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        SongBuilder {
            _state: PhantomData,
            _fields: (
                None, None, None, None, None, None, None, None, None, None, None, None,
            ),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SongBuilder<'a, S>
where
    S: song_state::State,
    S::AddedByDid: song_state::IsUnset,
{
    /// Set the `addedByDid` field (required)
    pub fn added_by_did(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> SongBuilder<'a, song_state::SetAddedByDid<S>> {
        self._fields.0 = Option::Some(value.into());
        SongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: song_state::State> SongBuilder<'a, S> {
    /// Set the `album` field (optional)
    pub fn album(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `album` field to an Option value (optional)
    pub fn maybe_album(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S> SongBuilder<'a, S>
where
    S: song_state::State,
    S::Artist: song_state::IsUnset,
{
    /// Set the `artist` field (required)
    pub fn artist(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> SongBuilder<'a, song_state::SetArtist<S>> {
        self._fields.2 = Option::Some(value.into());
        SongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SongBuilder<'a, S>
where
    S: song_state::State,
    S::CreatedAt: song_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<i64>,
    ) -> SongBuilder<'a, song_state::SetCreatedAt<S>> {
        self._fields.3 = Option::Some(value.into());
        SongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: song_state::State> SongBuilder<'a, S> {
    /// Set the `durationSeconds` field (optional)
    pub fn duration_seconds(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `durationSeconds` field to an Option value (optional)
    pub fn maybe_duration_seconds(mut self, value: Option<i64>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<'a, S: song_state::State> SongBuilder<'a, S> {
    /// Set the `genre` field (optional)
    pub fn genre(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `genre` field to an Option value (optional)
    pub fn maybe_genre(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<'a, S> SongBuilder<'a, S>
where
    S: song_state::State,
    S::HasCover: song_state::IsUnset,
{
    /// Set the `hasCover` field (required)
    pub fn has_cover(
        mut self,
        value: impl Into<bool>,
    ) -> SongBuilder<'a, song_state::SetHasCover<S>> {
        self._fields.6 = Option::Some(value.into());
        SongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SongBuilder<'a, S>
where
    S: song_state::State,
    S::Id: song_state::IsUnset,
{
    /// Set the `id` field (required)
    pub fn id(mut self, value: impl Into<CowStr<'a>>) -> SongBuilder<'a, song_state::SetId<S>> {
        self._fields.7 = Option::Some(value.into());
        SongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: song_state::State> SongBuilder<'a, S> {
    /// Set the `loudnessLufs` field (optional)
    pub fn loudness_lufs(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.8 = value.into();
        self
    }
    /// Set the `loudnessLufs` field to an Option value (optional)
    pub fn maybe_loudness_lufs(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.8 = value;
        self
    }
}

impl<'a, S: song_state::State> SongBuilder<'a, S> {
    /// Set the `loudnessPeak` field (optional)
    pub fn loudness_peak(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.9 = value.into();
        self
    }
    /// Set the `loudnessPeak` field to an Option value (optional)
    pub fn maybe_loudness_peak(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.9 = value;
        self
    }
}

impl<'a, S: song_state::State> SongBuilder<'a, S> {
    /// Set the `mimeType` field (optional)
    pub fn mime_type(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.10 = value.into();
        self
    }
    /// Set the `mimeType` field to an Option value (optional)
    pub fn maybe_mime_type(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.10 = value;
        self
    }
}

impl<'a, S> SongBuilder<'a, S>
where
    S: song_state::State,
    S::Title: song_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> SongBuilder<'a, song_state::SetTitle<S>> {
        self._fields.11 = Option::Some(value.into());
        SongBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SongBuilder<'a, S>
where
    S: song_state::State,
    S::HasCover: song_state::IsSet,
    S::CreatedAt: song_state::IsSet,
    S::Id: song_state::IsSet,
    S::Artist: song_state::IsSet,
    S::Title: song_state::IsSet,
    S::AddedByDid: song_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Song<'a> {
        Song {
            added_by_did: self._fields.0.unwrap(),
            album: self._fields.1,
            artist: self._fields.2.unwrap(),
            created_at: self._fields.3.unwrap(),
            duration_seconds: self._fields.4,
            genre: self._fields.5,
            has_cover: self._fields.6.unwrap(),
            id: self._fields.7.unwrap(),
            loudness_lufs: self._fields.8,
            loudness_peak: self._fields.9,
            mime_type: self._fields.10,
            title: self._fields.11.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Song<'a> {
        Song {
            added_by_did: self._fields.0.unwrap(),
            album: self._fields.1,
            artist: self._fields.2.unwrap(),
            created_at: self._fields.3.unwrap(),
            duration_seconds: self._fields.4,
            genre: self._fields.5,
            has_cover: self._fields.6.unwrap(),
            id: self._fields.7.unwrap(),
            loudness_lufs: self._fields.8,
            loudness_peak: self._fields.9,
            mime_type: self._fields.10,
            title: self._fields.11.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn _default_song_url_source_add_to_queue() -> Option<bool> {
    Some(false)
}

pub mod song_url_source_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Url;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Url = Unset;
    }
    ///State transition - sets the `url` field to Set
    pub struct SetUrl<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUrl<S> {}
    impl<S: State> State for SetUrl<S> {
        type Url = Set<members::url>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `url` field
        pub struct url(());
    }
}

/// Builder for constructing an instance of this type
pub struct SongUrlSourceBuilder<'a, S: song_url_source_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (
        Option<bool>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<CowStr<'a>>,
        Option<UriValue<'a>>,
    ),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> SongUrlSource<'a> {
    /// Create a new builder for this type
    pub fn new() -> SongUrlSourceBuilder<'a, song_url_source_state::Empty> {
        SongUrlSourceBuilder::new()
    }
}

impl<'a> SongUrlSourceBuilder<'a, song_url_source_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        SongUrlSourceBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: song_url_source_state::State> SongUrlSourceBuilder<'a, S> {
    /// Set the `addToQueue` field (optional)
    pub fn add_to_queue(mut self, value: impl Into<Option<bool>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `addToQueue` field to an Option value (optional)
    pub fn maybe_add_to_queue(mut self, value: Option<bool>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<'a, S: song_url_source_state::State> SongUrlSourceBuilder<'a, S> {
    /// Set the `album` field (optional)
    pub fn album(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `album` field to an Option value (optional)
    pub fn maybe_album(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<'a, S: song_url_source_state::State> SongUrlSourceBuilder<'a, S> {
    /// Set the `artist` field (optional)
    pub fn artist(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `artist` field to an Option value (optional)
    pub fn maybe_artist(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<'a, S: song_url_source_state::State> SongUrlSourceBuilder<'a, S> {
    /// Set the `title` field (optional)
    pub fn title(mut self, value: impl Into<Option<CowStr<'a>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `title` field to an Option value (optional)
    pub fn maybe_title(mut self, value: Option<CowStr<'a>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<'a, S> SongUrlSourceBuilder<'a, S>
where
    S: song_url_source_state::State,
    S::Url: song_url_source_state::IsUnset,
{
    /// Set the `url` field (required)
    pub fn url(
        mut self,
        value: impl Into<UriValue<'a>>,
    ) -> SongUrlSourceBuilder<'a, song_url_source_state::SetUrl<S>> {
        self._fields.4 = Option::Some(value.into());
        SongUrlSourceBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> SongUrlSourceBuilder<'a, S>
where
    S: song_url_source_state::State,
    S::Url: song_url_source_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> SongUrlSource<'a> {
        SongUrlSource {
            add_to_queue: self._fields.0.or_else(|| Some(false)),
            album: self._fields.1,
            artist: self._fields.2,
            title: self._fields.3,
            url: self._fields.4.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> SongUrlSource<'a> {
        SongUrlSource {
            add_to_queue: self._fields.0.or_else(|| Some(false)),
            album: self._fields.1,
            artist: self._fields.2,
            title: self._fields.3,
            url: self._fields.4.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}
