// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pet.nkp.radio.playlists.modify
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::pet_nkp::radio::Playlist;
use crate::pet_nkp::radio::RadioSnapshot;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Deserialize, Serialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Modify<'a> {
    ///Playlist operation to perform. Required companion fields are enforced by the server.
    #[serde(borrow)]
    pub action: ModifyAction<'a>,
    ///New playlist name for create, rename, and duplicate.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub name: Option<CowStr<'a>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub playlist_id: Option<CowStr<'a>>,
    ///One-based track position to drop when action is removeTrack.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub position: Option<i64>,
    /// Defaults to `false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default = "_default_modify_replace")]
    pub replace: Option<bool>,
    ///Overrides the playlist's stored shuffleOnLoad for this load only.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shuffle: Option<bool>,
    ///Whether loading this playlist randomizes its order.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shuffle_on_load: Option<bool>,
    ///Track song ids: the full contents for create, the appended tracks for addTracks, the complete new order for reorder.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub song_ids: Option<Vec<CowStr<'a>>>,
}

/// Playlist operation to perform. Required companion fields are enforced by the server.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ModifyAction<'a> {
    Create,
    Delete,
    Load,
    Rename,
    AddTracks,
    RemoveTrack,
    Reorder,
    Duplicate,
    SetShuffleOnLoad,
    SequenceTracks,
    Other(CowStr<'a>),
}

impl<'a> ModifyAction<'a> {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Create => "create",
            Self::Delete => "delete",
            Self::Load => "load",
            Self::Rename => "rename",
            Self::AddTracks => "addTracks",
            Self::RemoveTrack => "removeTrack",
            Self::Reorder => "reorder",
            Self::Duplicate => "duplicate",
            Self::SetShuffleOnLoad => "setShuffleOnLoad",
            Self::SequenceTracks => "sequenceTracks",
            Self::Other(s) => s.as_ref(),
        }
    }
}

impl<'a> From<&'a str> for ModifyAction<'a> {
    fn from(s: &'a str) -> Self {
        match s {
            "create" => Self::Create,
            "delete" => Self::Delete,
            "load" => Self::Load,
            "rename" => Self::Rename,
            "addTracks" => Self::AddTracks,
            "removeTrack" => Self::RemoveTrack,
            "reorder" => Self::Reorder,
            "duplicate" => Self::Duplicate,
            "setShuffleOnLoad" => Self::SetShuffleOnLoad,
            "sequenceTracks" => Self::SequenceTracks,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> From<String> for ModifyAction<'a> {
    fn from(s: String) -> Self {
        match s.as_str() {
            "create" => Self::Create,
            "delete" => Self::Delete,
            "load" => Self::Load,
            "rename" => Self::Rename,
            "addTracks" => Self::AddTracks,
            "removeTrack" => Self::RemoveTrack,
            "reorder" => Self::Reorder,
            "duplicate" => Self::Duplicate,
            "setShuffleOnLoad" => Self::SetShuffleOnLoad,
            "sequenceTracks" => Self::SequenceTracks,
            _ => Self::Other(CowStr::from(s)),
        }
    }
}

impl<'a> core::fmt::Display for ModifyAction<'a> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl<'a> AsRef<str> for ModifyAction<'a> {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl<'a> serde::Serialize for ModifyAction<'a> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de, 'a> serde::Deserialize<'de> for ModifyAction<'a>
where
    'de: 'a,
{
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = <&'de str>::deserialize(deserializer)?;
        Ok(Self::from(s))
    }
}

impl<'a> Default for ModifyAction<'a> {
    fn default() -> Self {
        Self::Other(Default::default())
    }
}

impl jacquard_common::IntoStatic for ModifyAction<'_> {
    type Output = ModifyAction<'static>;
    fn into_static(self) -> Self::Output {
        match self {
            ModifyAction::Create => ModifyAction::Create,
            ModifyAction::Delete => ModifyAction::Delete,
            ModifyAction::Load => ModifyAction::Load,
            ModifyAction::Rename => ModifyAction::Rename,
            ModifyAction::AddTracks => ModifyAction::AddTracks,
            ModifyAction::RemoveTrack => ModifyAction::RemoveTrack,
            ModifyAction::Reorder => ModifyAction::Reorder,
            ModifyAction::Duplicate => ModifyAction::Duplicate,
            ModifyAction::SetShuffleOnLoad => ModifyAction::SetShuffleOnLoad,
            ModifyAction::SequenceTracks => ModifyAction::SequenceTracks,
            ModifyAction::Other(v) => ModifyAction::Other(v.into_static()),
        }
    }
}

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct ModifyOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub playlist: Option<Playlist<'a>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub snapshot: Option<RadioSnapshot<'a>>,
}

#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic,
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ModifyError<'a> {
    #[serde(rename = "AuthenticationRequired")]
    AuthenticationRequired(Option<CowStr<'a>>),
    #[serde(rename = "AdminRequired")]
    AdminRequired(Option<CowStr<'a>>),
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<CowStr<'a>>),
    #[serde(rename = "PlaylistNotFound")]
    PlaylistNotFound(Option<CowStr<'a>>),
}

impl core::fmt::Display for ModifyError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AuthenticationRequired(msg) => {
                write!(f, "AuthenticationRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::AdminRequired(msg) => {
                write!(f, "AdminRequired")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::PlaylistNotFound(msg) => {
                write!(f, "PlaylistNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for pet.nkp.radio.playlists.modify
pub struct ModifyResponse;
impl jacquard_common::xrpc::XrpcResp for ModifyResponse {
    const NSID: &'static str = "pet.nkp.radio.playlists.modify";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ModifyOutput<'de>;
    type Err<'de> = ModifyError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for Modify<'a> {
    const NSID: &'static str = "pet.nkp.radio.playlists.modify";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = ModifyResponse;
}

/// Endpoint type for pet.nkp.radio.playlists.modify
pub struct ModifyRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ModifyRequest {
    const PATH: &'static str = "/xrpc/pet.nkp.radio.playlists.modify";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<'de> = Modify<'de>;
    type Response = ModifyResponse;
}

fn _default_modify_replace() -> Option<bool> {
    Some(false)
}
